version = 0.1
[default.deploy.parameters]
stack_name = "Memora-NotifyPageUpdate"
resolve_s3 = true
s3_prefix = "Memora-NotifyPageUpdate"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
