version = 0.1
[default.deploy.parameters]
stack_name = "ConfluenceContentIngestion"
resolve_s3 = true
s3_prefix = "ConfluenceContentIngestion"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
