AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Memora AI - Ingestion and Processing Stack

Globals:
  Function:
    Timeout: 900
    Runtime: python3.11
    MemorySize: 256

Resources:
  ContextIngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MemoraAI-ConfluenceContentIngestionFunction
      Description: Ingests content from Confluence and stores it in S3
      Handler: app.lambda_handler
      CodeUri: src/
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3WritePolicy:
            BucketName: memora-ai-ingestion-bucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:685148108183:secret:memora/*
      Environment:
        Variables:
          S3_BUCKET: memora-ai-ingestion-bucket
          S3_PREFIX: clean-data
          confluence_base_url: https://ashipj.atlassian.net/wiki
          confluence_email: ashipj@gmail.com
          CONFLUENCE_TOKEN: '{{resolve:secretsmanager:memora/email-confluence-secrets:SecretString:CONFLUENCE_TOKEN}}'